package com.edu.entry;

import java.util.Date;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.url
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.title
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.tag
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.likes
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.time
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.url
     *
     * @return the value of photo.url
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.url
     *
     * @param url the value for photo.url
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.title
     *
     * @return the value of photo.title
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.title
     *
     * @param title the value for photo.title
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.tag
     *
     * @return the value of photo.tag
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.tag
     *
     * @param tag the value for photo.tag
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.likes
     *
     * @return the value of photo.likes
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.likes
     *
     * @param likes the value for photo.likes
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.time
     *
     * @return the value of photo.time
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.time
     *
     * @param time the value for photo.time
     *
     * @mbg.generated Sat Apr 04 10:31:14 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}